package portforward

import (
	"context"

	"github.com/spf13/cobra"
	"github.com/wim-web/tnnl/cmd"
	"github.com/wim-web/tnnl/internal/handler"
	"github.com/wim-web/tnnl/internal/input"
)

var localPortName = "local-port"
var targetPortName = "target-port"
var inputFileName = "input-file"

type portforwardRunner func(context.Context, input.PortForwardInput) error

func newPortforwardCommand(run portforwardRunner) *cobra.Command {
	c := &cobra.Command{
		Use:   "portforward",
		Short: "Forward a local port to an ECS container",
		Long: "Forward a local port to an eligible ECS container.\n\n" +
			"Input values use this precedence: explicit flag > input JSON > default.\n" +
			"When the local port is omitted or the zero value (an empty string), tnnl uses\n" +
			"automatic local-port selection. Generate input with tnnl portforward make-input-file.",
		Example: "  tnnl portforward --target-port 8080\n" +
			"  tnnl portforward --input-file portforward-input.json\n" +
			"  tnnl portforward make-input-file",
		RunE: func(cmd *cobra.Command, args []string) error {
			path, err := cmd.Flags().GetString(inputFileName)
			if err != nil {
				return err
			}

			overrides := input.PortForwardOverrides{}
			if cmd.Flags().Changed(targetPortName) {
				value, err := cmd.Flags().GetString(targetPortName)
				if err != nil {
					return err
				}
				overrides.TargetPort = &value
			}
			if cmd.Flags().Changed(localPortName) {
				value, err := cmd.Flags().GetString(localPortName)
				if err != nil {
					return err
				}
				overrides.LocalPort = &value
			}

			resolved, err := input.ResolvePortForward(path, overrides)
			if err != nil {
				return err
			}
			return run(cmd.Context(), resolved)
		},
	}
	c.Flags().StringP(localPortName, "l", "", "local port; omit it (empty zero value) for automatic local-port selection; precedence: explicit flag > input JSON > default")
	c.Flags().StringP(targetPortName, "t", "", "target port; precedence: explicit flag > input JSON > default; a value is required")
	c.Flags().String(inputFileName, "", "input JSON generated by tnnl portforward make-input-file; explicit flags override input JSON values")
	return c
}

var PortforwardCmd = newPortforwardCommand(handler.PortforwardHandler)

func init() {
	cmd.RootCmd.AddCommand(PortforwardCmd)
}
