package remoteportforward

import (
	"context"

	"github.com/spf13/cobra"
	"github.com/wim-web/tnnl/cmd"
	"github.com/wim-web/tnnl/internal/handler"
	"github.com/wim-web/tnnl/internal/input"
)

var localPortName = "local-port"
var remotePortName = "remote-port"
var hostName = "host"
var inputFileName = "input-file"

type remotePortforwardRunner func(context.Context, input.RemotePortForwardInput) error

func newRemotePortforwardCommand(run remotePortforwardRunner) *cobra.Command {
	c := &cobra.Command{
		Use:   "remoteportforward",
		Short: "Forward a local port through an ECS container to a remote host",
		Long: "Forward a local port through an eligible ECS container to a remote host.\n\n" +
			"Input values use this precedence: explicit flag > input JSON > default.\n" +
			"When the local port is omitted or the zero value (an empty string), tnnl uses\n" +
			"automatic local-port selection. Generate input with tnnl remoteportforward make-input-file.",
		Example: "  tnnl remoteportforward --remote-port 3306 --host db.internal\n" +
			"  tnnl remoteportforward --input-file remoteportforward-input.json\n" +
			"  tnnl remoteportforward make-input-file",
		RunE: func(cmd *cobra.Command, args []string) error {
			path, err := cmd.Flags().GetString(inputFileName)
			if err != nil {
				return err
			}

			overrides := input.RemotePortForwardOverrides{}
			if cmd.Flags().Changed(remotePortName) {
				value, err := cmd.Flags().GetString(remotePortName)
				if err != nil {
					return err
				}
				overrides.RemotePort = &value
			}
			if cmd.Flags().Changed(localPortName) {
				value, err := cmd.Flags().GetString(localPortName)
				if err != nil {
					return err
				}
				overrides.LocalPort = &value
			}
			if cmd.Flags().Changed(hostName) {
				value, err := cmd.Flags().GetString(hostName)
				if err != nil {
					return err
				}
				overrides.Host = &value
			}

			resolved, err := input.ResolveRemotePortForward(path, overrides)
			if err != nil {
				return err
			}
			return run(cmd.Context(), resolved)
		},
	}
	c.Flags().StringP(localPortName, "l", "", "local port; omit it (empty zero value) for automatic local-port selection; precedence: explicit flag > input JSON > default")
	c.Flags().StringP(remotePortName, "r", "", "remote port; precedence: explicit flag > input JSON > default; a value is required")
	c.Flags().String(hostName, "", "remote host; precedence: explicit flag > input JSON > default; a value is required")
	c.Flags().String(inputFileName, "", "input JSON generated by tnnl remoteportforward make-input-file; explicit flags override input JSON values")
	return c
}

var RemoteportforwardCmd = newRemotePortforwardCommand(handler.RemotePortforwardHandler)

func init() {
	cmd.RootCmd.AddCommand(RemoteportforwardCmd)
}
